CREATE TABLE IF NOT EXISTS CUSTOMER (
CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
MOBILE_NUMBER VARCHAR(20) NOT NULL,
CREATED_AT DATE NOT NULL,
CREATED_BY VARCHAR(100) NOT NULL,
UPDATED_AT DATE,
UPDATED_BY VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ACCOUNTS
(
CUSTOMER_ID INT NOT NULL,
ACCOUNT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNT_TYPE VARCHAR(100) NOT NULL,
BRANCH_ADDRESS VARCHAR(20) NOT NULL,
CREATED_AT DATE NOT NULL,
CREATED_BY VARCHAR(100) NOT NULL,
UPDATED_AT DATE,
UPDATED_BY VARCHAR(100)
);